version: "3.8"

services:

  postgres:
    container_name: postgres_db1
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./envs/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trading-system"]
      interval: 10s
      timeout: 5s
      retries: 5

  trading_system:
    container_name: trading1
    build: trading-system
    volumes:
      - ./logs:/app/logs
      - ./trading-system:/app
    env_file:
      - ./envs/parsing.env
      - ./envs/db.env
      - ./envs/management.env
      - ./envs/trading.env
      - ./envs/market.env
      - ./envs/llm.env
    depends_on:
      postgres:
        condition: service_healthy

  management_service:
    container_name: management1
    build: ./management-service
    volumes:
      - ./management-service:/app
    ports:
      - "8080:8080"
    env_file:
      - ./envs/management.env
      - ./envs/market.env
      - ./envs/db.env

volumes:
  postgres_data:

networks:
  default:
    name: trading_network
