version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    env_file:
      - ./envs/llm.env
    volumes:
      - ./ollama/models:/root/.ollama
      - ./ollama/install.sh:/install.sh
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "bash", "-c", "ollama list | awk 'NR>1' | grep -q ."]
      interval: 30s
      timeout: 10s
      retries: 5
    entrypoint: ["bash", "/install.sh"]

  postgres:
    container_name: postgres_db1
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./envs/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trading-system"]
      interval: 10s
      timeout: 5s
      retries: 5

  trading_system:
    container_name: trading1
    build: trading-system
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Проброс хоста Linux в контейнер
    volumes:
      - ./logs:/app/logs
      - ./trading-system:/app
    env_file:
      - ./envs/parsing.env
      - ./envs/db.env
      - ./envs/management.env
      - ./envs/trading.env
      - ./envs/market.env
      - ./envs/llm.env
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy

  management_service:
    container_name: management1
    build: ./management-service
    volumes:
      - ./management-service:/app
    ports:
      - "8080:8080"
    env_file:
      - ./envs/management.env
      - ./envs/market.env
      - ./envs/db.env

volumes:
  postgres_data:

networks:
  default:
    name: trading_network
