version: "3.8"

services:
  backtest-service:
    build:
      context: ./sync
    volumes:
      - ./sync:/app
      - ./backtesting_session.session:/app/backtesting_session.session
    env_file:
      - ./backtest_service.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backtest_db.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  default:
    name: backtest_network_dev
